# Generated by Django 4.2.13 on 2024-07-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodel_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='chat_id',
            new_name='telegram_chat_id',
        ),
    ]
