# Generated by Django 4.2.13 on 2024-07-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_chat_id_usermodel_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='telegram_verif_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
