# Generated by Django 4.2.13 on 2024-07-13 18:19

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_clubmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
