# Generated by Django 4.2.13 on 2024-07-16 10:37

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_clubmodel_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmodel',
            name='desc',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='clubmodel',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Полное описание'),
        ),
    ]
