# Generated by Django 4.2.13 on 2024-07-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0004_alter_clubmodel_desc_alter_clubmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='required_team',
            field=models.TextField(blank=True, null=True, verbose_name='Требуются в команду'),
        ),
    ]
