# Generated by Django 4.2.13 on 2024-07-16 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collab', '0005_clubmodel_required_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='request_team',
            field=models.ManyToManyField(blank=True, related_name='request_team_club_model', to=settings.AUTH_USER_MODEL, verbose_name='Заявки на участие'),
        ),
        migrations.AlterField(
            model_name='clubmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_club_model', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
