# Generated by Django 4.2.13 on 2024-07-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0006_clubmodel_request_team_alter_clubmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
    ]
