# Generated by Django 4.2.13 on 2024-07-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0007_clubmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
