# Generated by Django 4.2.14 on 2024-08-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0012_remove_club_author_remove_club_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
